import { RootNavbar } from "@/components/Navbar";
import MobileSheet from "@/components/MobileSheet";
import BreadcrumbComponent from "@/components/BreadcrumbComponent";
import { createClient } from "@/lib/supabase/server";
import { Button } from "@/components/ui/Button";
import Link from "next/link";

import UserDropdown from "@/components/UserDropdown";
import { getUser } from "@/lib/supabase/queries";

export const metadata = {
  title: "Keepalive | Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();
  const user = await getUser(supabase);

  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
      <RootNavbar />
      <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
          <MobileSheet />
          <BreadcrumbComponent />
          <div className="relative ml-auto grow-0">
            {user !== null ? (
              <UserDropdown user={user} />
            ) : (
              <Button>
                <Link href="/login">Sign in</Link>
              </Button>
            )}
          </div>
        </header>
        <main className="grid flex-1 items-start p-4">{children}</main>
      </div>
    </div>
  );
}
