import LandingFooter from "@/components/landing/LandingFooter";
import LandingNavbar from "@/components/landing/LandingNavbar";

export const metadata = {
  title: "Keepalive | Internet Learning",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function LandingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-white to-red-100 dark:from-black dark:to-gray-700">
        <div className="flex min-h-[100dvh] flex-col ">
          <LandingNavbar />
          <main className="flex flex-col md:mx-8">{children}</main>
          <LandingFooter />
        </div>
      </body>
    </html>
  );
}
