import LandingFooter from "@/components/landing/LandingFooter";
import LandingNavbar from "@/components/landing/LandingNavbar";

export const metadata = {
  title: "Arcana | Keep Learning",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function LandingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className="bg-gradient-to-b from-white to-red-50">
      <div className="flex min-h-[100dvh] flex-col ">
        <LandingNavbar />
        <main className="mx-8 flex flex-col">{children}</main>
        <LandingFooter />
      </div>
    </body>
  );
}
