import { RootNavbar } from "@/components/Navbar";
import { Input } from "@/components/ui/Input";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Search } from "lucide-react";
import MobileSheet from "@/components/MobileSheet";
import UserDropdown from "@/components/UserDropdown";
import BreadcrumbComponent from "@/components/BreadcrumbComponent";

export const metadata = {
  title: "Arcana | Keep Learning",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <div className="bg-muted/40 flex min-h-screen w-full flex-col">
          <RootNavbar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <header className="bg-background sticky top-0 z-30 flex h-14 items-center gap-4 border-b px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
              <MobileSheet />
              <BreadcrumbComponent />
              <div className="relative ml-auto flex-1 md:grow-0">
                <Search className="text-muted-foreground absolute left-2.5 top-2.5 h-4 w-4" />
                <Input
                  type="search"
                  placeholder="Search..."
                  className="bg-background w-full rounded-lg pl-8 md:w-[200px] lg:w-[336px]"
                />
              </div>
              <UserDropdown />
            </header>
            <main className="grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8 lg:grid-cols-3 xl:grid-cols-3">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
