import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { Rhodium_Libre } from "next/font/google";
import { Kanit } from "next/font/google";

export const metadata = {
  title: "Arcana | Keep Learning",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const rhodium_libre = Rhodium_Libre({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rhodium-libre",
});

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-kanit",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${rhodium_libre.variable} ${kanit.variable}`}
    >
      <body className="bg-gradient-to-b from-white to-red-100 dark:bg-black dark:from-black dark:to-gray-700">
        {children}
      </body>
    </html>
  );
}
